{% set name = "pylev" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9e77e941042ad3a4cc305dcdf2b2dec1aec2fbe3dd9015d2698ad02b173006d1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.3
    - pip
  run:
    - python >=3.3

test:
  imports:
    - pylev

about:
  home: http://github.com/toastdriven/pylev
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A pure Python Levenshtein implementation that's not freaking GPL'd.
  description: A pure Python Levenshtein implementation that's not freaking GPL'd. Based off the Wikipedia code samples at http://en.wikipedia.org/wiki/Levenshtein_distance.
  doc_url: https://pypi.org/project/pylev/
  dev_url: https://github.com/toastdriven/pylev

extra:
  recipe-maintainers:
    - nick-youngblut
